# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Trung Le
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupybase
project_short_description: A JupyterLab extension.
python_name: jupybase
repository: ''
test: false

