export const NEXT_PUBLIC_SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL || '{@{NEXT_PUBLIC_SUPABASE_URL}@}';

export const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  '{@{NEXT_PUBLIC_SUPABASE_ANON_KEY}@}';

export const MAIN_APP_PUBLIC_URL =
  process.env.MAIN_APP_PUBLIC_URL || '{@{MAIN_APP_PUBLIC_URL}@}';

console.log(
  '%%%%%%%%',
  NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY,
  MAIN_APP_PUBLIC_URL
);
